/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Craig Hu's blog",
  "description": "一个吃货的网站",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/logo.jpg"
      }
    ]
  ],
  "pages": [
    {
      "title": "第一章节, MD操作说明",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-71f9da98",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "1. 标题大小：",
          "slug": "_1-标题大小"
        },
        {
          "level": 2,
          "title": "2. 换行：",
          "slug": "_2-换行"
        },
        {
          "level": 2,
          "title": "3. 文本字体：",
          "slug": "_3-文本字体"
        },
        {
          "level": 2,
          "title": "4.分割线，删除线，下划线",
          "slug": "_4-分割线-删除线-下划线"
        },
        {
          "level": 2,
          "title": "5.列表",
          "slug": "_5-列表"
        },
        {
          "level": 2,
          "title": "6.区块嵌套",
          "slug": "_6-区块嵌套"
        },
        {
          "level": 2,
          "title": "7.函数",
          "slug": "_7-函数"
        },
        {
          "level": 2,
          "title": "8.链接、图片",
          "slug": "_8-链接、图片"
        },
        {
          "level": 2,
          "title": "9.表格",
          "slug": "_9-表格"
        },
        {
          "level": 2,
          "title": "10.按钮",
          "slug": "_10-按钮"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "个人简介",
        "link": "/accumulate/"
      },
      {
        "text": "操作说明",
        "link": "/algorithm/"
      },
      {
        "text": "Github",
        "link": "https://github.com/ayanamirei629"
      }
    ],
    "sidebar": "auto",
    "sidebarDepth": 2
  }
}